spring:
  datasource:
    # 这里需要修改成自己的数据库账号
    username: root
    # 这里需要修改成自己的数据库密码
    password: admin
  sql:
    init:
      # 是否初始化数据库
      # always 总是（开发环境使用）
      # never 从不（生产环境使用）
      # embedded 嵌入式
      mode: never
  ai:
    openai:
      api-key: sk-f5d17c9584e94b1c992cd566f2e5b136